# Development Stack Requirements

system:
  os:
    - linux:  # Primary development platform
        packages:
          - gtk4
          - libadwaita-1
          - pkg-config
          - build-essential
    - macos:  # Supported through homebrew
        packages:
          - gtk4
          - libadwaita
          - pkg-config

runtime:
  desktop:
    - deno: "^1.37.0"
    - gtk4: ">=4.0.0"
    - libadwaita: ">=1.0.0"
    
  mobile:
    - nativescript: "^8.0.0"
    - android-sdk: ">=30"
    - xcode: ">=13.0"  # For iOS development

development:
  languages:
    - typescript: "^5.0.0"
    
  tools:
    - antlr4: "^4.13.0"
    - antlr4-typescript-target: "^1.0.0"
    
  ide_extensions:
    - "antlr4.grammar-editor"
    - "denoland.vscode-deno"
    - "nativescript.nativescript-extension"

ai_integration:
  tools:
    - aider:
        models:
          - openai-gpt4
          - deepseek-coder
          - anthropic-claude
          - google-gemini
    - cline:
        models:
          - openai-gpt4
          - deepseek-coder
          - anthropic-claude
          - google-gemini

ffi_bindings:
  gtk4:
    - gobject-2.0
    - gtk4
    - libadwaita-1
    headers:
      - gtk/gtk.h
      - adwaita.h

parsing:
  grammars:
    - typescript.g4
    - custom_extensions.g4
  
  targets:
    - typescript
    - javascript

build:
  desktop:
    - deno compile
    - ffi type generation
    - gtk resource bundling
  
  mobile:
    - nativescript build
    - platform-specific bundling

testing:
  frameworks:
    - deno test
    - nativescript test
  
  requirements:
    - unit testing
    - integration testing
    - ui testing
    - cross-platform testing

documentation:
  required:
    - api documentation
    - ffi bindings documentation
    - grammar documentation
    - build instructions
    - deployment guides
